"""Generate ``docs/generated/claims.md`` (and ``claims_kr.md``) from source-of-truth files.

Source of truth, in order of precedence:
- ``pyproject.toml`` — distribution name, version, Python requirement,
  runtime dependencies, optional extras, console scripts.
- ``src/mini_omega_lock/__init__.py`` — ``__version__``, ``__all__``.
- ``src/mini_omega_lock/mcp/server.py`` — registered MCP tool names
  (one per ``@mcp_app.tool()`` decorator).

Run modes::

    python scripts/generate_readme_claims.py            # write files
    python scripts/generate_readme_claims.py --check    # diff-only, exit 1 on drift

The ``--check`` exit code is used in CI and ``release_audit.py`` to detect
stale generated docs. The file format starts with an AUTOGENERATED banner
so a human editor knows not to hand-edit the rendered tables.

Implementation note: no third-party imports — runs on a fresh Python 3.11
checkout before ``pip install -e`` has been run, which makes this safe to
invoke very early in CI / release-audit pipelines.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
import tomllib
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = REPO_ROOT / "pyproject.toml"
INIT_PATH = REPO_ROOT / "src" / "mini_omega_lock" / "__init__.py"
MCP_SERVER_PATH = REPO_ROOT / "src" / "mini_omega_lock" / "mcp" / "server.py"
CLAIMS_EN = REPO_ROOT / "docs" / "generated" / "claims.md"
CLAIMS_KR = REPO_ROOT / "docs" / "generated" / "claims_kr.md"


# ---------------------------------------------------------------------------
# Source-of-truth readers
# ---------------------------------------------------------------------------


def load_pyproject() -> dict[str, Any]:
    return tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))


def read_module_constant(path: Path, name: str) -> Any:
    """Pull a literal top-level assignment without importing the module."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id == name:
                return ast.literal_eval(node.value)
    raise KeyError(f"{name!r} not found at module level in {path}")


def discover_mcp_tool_names(path: Path) -> list[str]:
    """Find every ``@mcp_app.tool()``-decorated function name in ``server.py``."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    names: list[str] = []
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef):
            continue
        for deco in node.decorator_list:
            # Match ``@mcp_app.tool()`` (Call) and ``@mcp_app.tool`` (Attribute).
            target = deco.func if isinstance(deco, ast.Call) else deco
            if isinstance(target, ast.Attribute) and target.attr == "tool":
                value = target.value
                if isinstance(value, ast.Name) and value.id == "mcp_app":
                    names.append(node.name)
    return names


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------


_BANNER = (
    "<!-- AUTOGENERATED: do not edit. -->\n"
    "<!-- Source: scripts/generate_readme_claims.py -->\n"
    "<!-- Regenerate: python scripts/generate_readme_claims.py -->\n"
    "<!-- Source of truth: pyproject.toml, "
    "src/mini_omega_lock/__init__.py, "
    "src/mini_omega_lock/mcp/server.py -->\n"
)


def _bullet(items: list[str]) -> str:
    return "\n".join(f"- `{item}`" for item in items)


def _format_deps(deps: list[str]) -> str:
    return ", ".join(f"`{d}`" for d in deps)


def _format_extras(extras: dict[str, list[str]]) -> str:
    return "; ".join(f"`{name}` = {_format_deps(pins)}" for name, pins in extras.items())


def _scripts_lines(scripts: dict[str, str]) -> str:
    return "\n".join(f"- `{name}` → `{target}`" for name, target in scripts.items())


def _parse_omegaprompt_pin(deps: list[str]) -> str:
    for d in deps:
        if d.startswith("omegaprompt"):
            return d
    return ""


def _badge_version(version: str) -> str:
    # Used by check_repo_consistency to compare README badge text.
    return version


# ---------------------------------------------------------------------------
# Render — English
# ---------------------------------------------------------------------------


def render_en(facts: dict[str, Any]) -> str:
    public_api = "\n".join(f"- `{name}`" for name in facts["public_api"])
    mcp_tools = "\n".join(f"- `{name}`" for name in facts["mcp_tools"])
    deps = _format_deps(facts["dependencies"])
    extras = _format_extras(facts["optional_dependencies"])
    scripts = _scripts_lines(facts["scripts"])
    return f"""{_BANNER}
# mini-omega-lock — generated claims

These tables are regenerated from `pyproject.toml`, `src/mini_omega_lock/__init__.py`, and `src/mini_omega_lock/mcp/server.py`. Any drift between this file and the source files is a release blocker — see `scripts/check_repo_consistency.py` for the gate.

## Distribution

| Claim | Value |
|---|---|
| GitHub repository | `hibou04-ops/{facts['name']}` |
| PyPI distribution | `{facts['name']}` |
| Python import package | `mini_omega_lock` |
| Package version (`pyproject.toml`) | `{facts['version']}` |
| Package version (`__init__.__version__`) | `{facts['init_version']}` |
| Requires Python | `{facts['requires_python']}` |
| Runtime dependencies | {deps} |
| Optional extras | {extras} |
| License | Apache-2.0 (see `LICENSE`) |

## Console scripts

{scripts}

## MCP

| Claim | Value |
|---|---|
| MCP optional extra | `mcp` (`pip install "{facts['name']}[mcp]"`) |
| MCP stdio command | `python -m mini_omega_lock.mcp` |
| MCP streamable-http command | `python -m mini_omega_lock.mcp --http` |
| Registered tool count | `{len(facts['mcp_tools'])}` |

### Registered MCP tools

{mcp_tools}

## Public API (`mini_omega_lock.__all__`)

{public_api}

## Install commands

```bash
# Library only
pip install {facts['name']}

# Library + MCP server
pip install "{facts['name']}[mcp]"

# Library + tests
pip install "{facts['name']}[dev]"

# Library + tests + MCP (editable, used by CI)
pip install -e ".[dev,mcp]"
```

## Verification commands

| Purpose | Command |
|---|---|
| Deterministic test suite (offline) | `python -m pytest -q` |
| Regenerate this file | `python scripts/generate_readme_claims.py` |
| Generated claims drift check | `python scripts/generate_readme_claims.py --check` |
| Repository consistency check | `python scripts/check_repo_consistency.py` |
| Deterministic demo replay | `python examples/demo_replay.py` |
| Offline golden cases (replay + diff) | `python scripts/run_golden_cases.py --check` |
| Fixture integrity (SHA-256 manifest) | `python scripts/verify_fixture_integrity.py` |
| Release audit (no-network) | `python scripts/release_audit.py --no-network` |
| Build wheel | `python -m build` |
| Wheel smoke install (temp venv) | `python scripts/wheel_smoke_install.py dist/{facts['name'].replace('-', '_')}-{facts['version']}-py3-none-any.whl` |
| Publish-readiness gate (no-network) | `python scripts/publish_readiness.py --no-network` |
| Post-release verification (no-network) | `python scripts/post_release_verify.py --no-network` |

## What these claims are NOT

- Not a proof that the package works against live providers — default tests and default CI are offline.
- Not a benchmark of model quality, judge quality, or provider reliability.
- Not a fixed test count — `pytest -q` is the source of truth. The number of MCP-skipped tests depends on whether the `mcp` extra is installed.
- Not a claim about production adoption.

See `docs/claim_ledger.md` for the full claim-to-source mapping.
"""


# ---------------------------------------------------------------------------
# Render — Korean (mirror structure; identifiers stay in English)
# ---------------------------------------------------------------------------


def render_kr(facts: dict[str, Any]) -> str:
    public_api = "\n".join(f"- `{name}`" for name in facts["public_api"])
    mcp_tools = "\n".join(f"- `{name}`" for name in facts["mcp_tools"])
    deps = _format_deps(facts["dependencies"])
    extras = _format_extras(facts["optional_dependencies"])
    scripts = _scripts_lines(facts["scripts"])
    return f"""{_BANNER}
# mini-omega-lock — 자동 생성된 사실 (Generated claims)

이 표는 `pyproject.toml`, `src/mini_omega_lock/__init__.py`, `src/mini_omega_lock/mcp/server.py`로부터 다시 생성됩니다. 이 파일과 원천 파일 사이의 불일치는 release blocker로 취급합니다 — 검사는 `scripts/check_repo_consistency.py`.

## 배포 정보 (Distribution)

| 항목 | 값 |
|---|---|
| GitHub 저장소 | `hibou04-ops/{facts['name']}` |
| PyPI 배포 이름 | `{facts['name']}` |
| Python import 패키지명 | `mini_omega_lock` |
| 패키지 버전 (`pyproject.toml`) | `{facts['version']}` |
| 패키지 버전 (`__init__.__version__`) | `{facts['init_version']}` |
| 지원 Python | `{facts['requires_python']}` |
| 런타임 의존성 | {deps} |
| Optional extras | {extras} |
| 라이선스 | Apache-2.0 (`LICENSE` 참조) |

## 콘솔 스크립트 (Console scripts)

{scripts}

## MCP

| 항목 | 값 |
|---|---|
| MCP optional extra | `mcp` (`pip install "{facts['name']}[mcp]"`) |
| MCP stdio 명령 | `python -m mini_omega_lock.mcp` |
| MCP streamable-http 명령 | `python -m mini_omega_lock.mcp --http` |
| 등록된 도구 개수 | `{len(facts['mcp_tools'])}` |

### 등록된 MCP 도구

{mcp_tools}

## Public API (`mini_omega_lock.__all__`)

{public_api}

## 설치 명령

```bash
# 라이브러리만
pip install {facts['name']}

# 라이브러리 + MCP 서버
pip install "{facts['name']}[mcp]"

# 라이브러리 + 테스트
pip install "{facts['name']}[dev]"

# 라이브러리 + 테스트 + MCP (CI 모드)
pip install -e ".[dev,mcp]"
```

## 검증 명령

| 목적 | 명령 |
|---|---|
| 결정론적 테스트 (오프라인) | `python -m pytest -q` |
| 이 파일 재생성 | `python scripts/generate_readme_claims.py` |
| 생성 문서 drift 검사 | `python scripts/generate_readme_claims.py --check` |
| 저장소 정합성 검사 | `python scripts/check_repo_consistency.py` |
| 결정론적 demo replay | `python examples/demo_replay.py` |
| 오프라인 golden case (replay + diff) | `python scripts/run_golden_cases.py --check` |
| Fixture 무결성 (SHA-256 manifest) | `python scripts/verify_fixture_integrity.py` |
| Release 감사 (no-network) | `python scripts/release_audit.py --no-network` |
| 휠 빌드 | `python -m build` |
| 휠 smoke 설치 (임시 venv) | `python scripts/wheel_smoke_install.py dist/{facts['name'].replace('-', '_')}-{facts['version']}-py3-none-any.whl` |
| Publish-readiness 게이트 (no-network) | `python scripts/publish_readiness.py --no-network` |
| Post-release 검증 (no-network) | `python scripts/post_release_verify.py --no-network` |

## 이 파일이 *아닌* 것

- Live provider 동작 보증 — 기본 테스트와 기본 CI는 오프라인입니다.
- 모델 품질, judge 품질, provider 신뢰도 벤치마크가 아님.
- 고정된 테스트 개수가 아님 — `pytest -q` 결과가 source of truth. MCP-skip 테스트 개수는 `mcp` extra 설치 여부에 따라 달라집니다.
- 프로덕션 도입 사례를 주장하는 문서가 아님.

전체 claim-to-source 매핑은 `docs/claim_ledger_kr.md`를 참조.
"""


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def collect_facts() -> dict[str, Any]:
    pp = load_pyproject()
    project = pp["project"]
    return {
        "name": project["name"],
        "version": project["version"],
        "init_version": read_module_constant(INIT_PATH, "__version__"),
        "requires_python": project["requires-python"],
        "dependencies": list(project.get("dependencies", [])),
        "optional_dependencies": {
            k: list(v) for k, v in project.get("optional-dependencies", {}).items()
        },
        "scripts": dict(project.get("scripts", {})),
        "public_api": list(read_module_constant(INIT_PATH, "__all__")),
        "mcp_tools": discover_mcp_tool_names(MCP_SERVER_PATH),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Re-render to memory and diff against disk; exit 1 on drift.",
    )
    args = parser.parse_args(argv)

    facts = collect_facts()
    rendered = {
        CLAIMS_EN: render_en(facts),
        CLAIMS_KR: render_kr(facts),
    }

    if args.check:
        drift: list[str] = []
        for path, content in rendered.items():
            if not path.exists():
                drift.append(f"missing: {path.relative_to(REPO_ROOT)}")
                continue
            current = path.read_text(encoding="utf-8")
            if current != content:
                drift.append(f"stale:   {path.relative_to(REPO_ROOT)}")
        if drift:
            print("Generated claims are stale:", file=sys.stderr)
            for line in drift:
                print(f"  {line}", file=sys.stderr)
            print(
                "Regenerate with: python scripts/generate_readme_claims.py",
                file=sys.stderr,
            )
            return 1
        print("Generated claims are up to date.")
        return 0

    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
